[package]
name = "baller"
version = "0.1.0"
edition = "2021"
authors = ["HMythical <baller.support@gmail.com>"]
description = "A package manager for Windows & Linux Similar to Chocolatey, but with a sense of syntactical humor!"
license = "Apache-2.0"
repository = "https://github.com/HMythical/baller.git"